FROM php:7.2-apache
RUN apt-get update && docker-php-ext-install pdo_mysql
RUN useradd toto
RUN usermod -a -G www-data toto
ENV APACHE_DOCUMENT_ROOT /path/to/new/root
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
